export * from './account.service';
import { AccountProxy } from './account.service';
export * from './configuration.service';
import { ConfigurationProxy } from './configuration.service';
export * from './dashboard.service';
import { DashboardProxy } from './dashboard.service';
export * from './gMSTransactionManager.service';
import { GMSTransactionManagerProxy } from './gMSTransactionManager.service';
export * from './groupParticipant.service';
import { GroupParticipantProxy } from './groupParticipant.service';
export * from './groupType.service';
import { GroupTypeProxy } from './groupType.service';
export * from './paymentStructure.service';
import { PaymentStructureProxy } from './paymentStructure.service';
export * from './role.service';
import { RoleProxy } from './role.service';
export * from './session.service';
import { SessionProxy } from './session.service';
export * from './tenant.service';
import { TenantProxy } from './tenant.service';
export * from './tokenAuth.service';
import { TokenAuthProxy } from './tokenAuth.service';
export * from './transactionManager.service';
import { TransactionManagerProxy } from './transactionManager.service';
export * from './user.service';
import { UserProxy } from './user.service';
export const APIS = [AccountProxy, ConfigurationProxy, DashboardProxy, GMSTransactionManagerProxy, GroupParticipantProxy, GroupTypeProxy, PaymentStructureProxy, RoleProxy, SessionProxy, TenantProxy, TokenAuthProxy, TransactionManagerProxy, UserProxy];
