export * from './account.service';
import { AccountProxy } from './account.service';
export * from './configuration.service';
import { ConfigurationProxy } from './configuration.service';
export * from './gMSTransaction.service';
import { GMSTransactionProxy } from './gMSTransaction.service';
export * from './groupDetails.service';
import { GroupDetailsProxy } from './groupDetails.service';
export * from './groupParticipant.service';
import { GroupParticipantProxy } from './groupParticipant.service';
export * from './paymentStructure.service';
import { PaymentStructureProxy } from './paymentStructure.service';
export * from './role.service';
import { RoleProxy } from './role.service';
export * from './session.service';
import { SessionProxy } from './session.service';
export * from './tenant.service';
import { TenantProxy } from './tenant.service';
export * from './tokenAuth.service';
import { TokenAuthProxy } from './tokenAuth.service';
export * from './transications.service';
import { TransicationsProxy } from './transications.service';
export * from './user.service';
import { UserProxy } from './user.service';
export const APIS = [AccountProxy, ConfigurationProxy, GMSTransactionProxy, GroupDetailsProxy, GroupParticipantProxy, PaymentStructureProxy, RoleProxy, SessionProxy, TenantProxy, TokenAuthProxy, TransicationsProxy, UserProxy];
