/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthenticateResultModel { 
    accessToken?: string | null;
    encryptedAccessToken?: string | null;
    expireInSeconds?: number;
    userId?: number;
}

