/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CombinedTransactionDto } from './combinedTransactionDto';


export interface CombinedTransactionDtoPagedResultDto { 
    items?: Array<CombinedTransactionDto> | null;
    totalCount?: number;
}

