/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionType } from './transactionType';
import { MemberType } from './memberType';


export interface CombinedTransactionDto { 
    gmsTransactionId?: number;
    refNo?: string | null;
    date?: string;
    amount?: number;
    feeStructure?: string | null;
    participantRefNo?: string | null;
    memberType?: MemberType;
    userName?: string | null;
    transactionType?: TransactionType;
    email?: string | null;
    phoneNumber?: string | null;
}
export namespace CombinedTransactionDto {
}


