/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserDto { 
    userName: string;
    name: string;
    surname: string;
    emailAddress: string;
    isActive?: boolean;
    roleNames?: Array<string> | null;
    password: string;
}

