/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionSummaryDto } from './transactionSummaryDto';


export interface DashboardDto { 
    totalStudents?: number;
    totalTeachers?: number;
    monthlyRevenue?: number;
    recentTransactions?: Array<TransactionSummaryDto> | null;
}

