/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TenantLoginInfoDto } from './tenantLoginInfoDto';
import { UserLoginInfoDto } from './userLoginInfoDto';
import { ApplicationInfoDto } from './applicationInfoDto';


export interface GetCurrentLoginInformationsOutput { 
    application?: ApplicationInfoDto;
    user?: UserLoginInfoDto;
    tenant?: TenantLoginInfoDto;
}

