/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleEditDto } from './roleEditDto';
import { FlatPermissionDto } from './flatPermissionDto';


export interface GetRoleForEditOutput { 
    role?: RoleEditDto;
    permissions?: Array<FlatPermissionDto> | null;
    grantedPermissionNames?: Array<string> | null;
}

