/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GMSTransactionResponseDTO { 
    id?: number;
    groupMemberRefNO?: string | null;
    transactionDate?: string;
    transId?: number;
    amount?: number;
    status?: string | null;
    type?: string | null;
    mode?: string | null;
    transactionReferenceId?: string | null;
    paymentStructureName?: string | null;
    paymentStructureId?: number;
}

