/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionType } from './transactionType';
import { TransactionMode } from './transactionMode';
import { TransactionStatus } from './transactionStatus';


export interface GMSTransactionResponseDTO { 
    id?: number;
    refNo?: string | null;
    date?: string;
    amount?: number;
    transId?: number;
    status?: TransactionStatus;
    mode?: TransactionMode;
    type?: TransactionType;
    paymentStructureId?: number;
}
export namespace GMSTransactionResponseDTO {
}


