/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GMSTransactionResponseDTO } from './gMSTransactionResponseDTO';


export interface GMSTransactionResponseDTOAPIResponse { 
    result?: GMSTransactionResponseDTO;
    message?: string | null;
}

