/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupDetailsResponseDTO { 
    id?: number;
    groupName?: string | null;
    userId?: number;
    chairmanName?: string | null;
    chairmanMobileNumber?: string | null;
    groupRegion?: string | null;
    groupDistrict?: string | null;
    groupWard?: string | null;
    officeNumber?: string | null;
    groupNumber?: string | null;
    memberId?: number;
    typeId?: number;
    policyId?: number;
    groupTypeId?: number;
    frequency?: string | null;
}

