/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemberType } from './memberType';


export interface GroupParticipantRequestDTO { 
    memberType?: MemberType;
    userName?: string | null;
    emial?: string | null;
    phoneNumber?: string | null;
    groupTypeId?: number;
}
export namespace GroupParticipantRequestDTO {
}


