/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemberType } from './memberType';


export interface GroupParticipantResponseDTO { 
    id?: number;
    memberType?: MemberType;
    groupMemberRefNO?: string | null;
    groupId?: number;
    userName?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
}
export namespace GroupParticipantResponseDTO {
}


