/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GMSGroupType } from './gMSGroupType';


export interface GroupDetailsRequestDTO { 
    groupName?: string | null;
    chairmanName?: string | null;
    chairmanMobileNumber?: string | null;
    groupRegion?: string | null;
    groupDistrict?: string | null;
    groupWard?: string | null;
    officeNumber?: string | null;
    groupNumber?: string | null;
    memberId?: number;
    typeId?: number;
    policyId?: number;
    groupType?: GMSGroupType;
    frequency?: string | null;
}
export namespace GroupDetailsRequestDTO {
}


