/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupParticipantResponseDTO } from './groupParticipantResponseDTO';


export interface GroupParticipantResponseDTOPagedResultDto { 
    items?: Array<GroupParticipantResponseDTO> | null;
    totalCount?: number;
}

