/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TenantAvailabilityState } from './tenantAvailabilityState';


export interface IsTenantAvailableOutput { 
    state?: TenantAvailabilityState;
    tenantId?: number | null;
}
export namespace IsTenantAvailableOutput {
}


