/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentStructureRequestDTO { 
    groupTypeId?: number;
    name?: string | null;
    amount?: number;
    groupId?: number;
}

