/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentStructureResponseDTO } from './paymentStructureResponseDTO';


export interface PaymentStructureResponseDTOAPIResponse { 
    result?: PaymentStructureResponseDTO;
    message?: string | null;
}

