/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleListDto } from './roleListDto';


export interface RoleListDtoListResultDto { 
    items?: Array<RoleListDto> | null;
}

