/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GMSTransactionResponseDTO } from './gMSTransactionResponseDTO';


export interface SchoolDashBoardDTO { 
    totalStudent?: number;
    toatalTeacher?: number;
    lastMonthCollections?: number;
    recenTransaction?: Array<GMSTransactionResponseDTO> | null;
}

