/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SchoolDashBoardDTO } from './schoolDashBoardDTO';


export interface SchoolDashBoardDTOAPIResponse { 
    result?: SchoolDashBoardDTO;
    message?: string | null;
}

