/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TenantDto } from './tenantDto';


export interface TenantDtoPagedResultDto { 
    items?: Array<TenantDto> | null;
    totalCount?: number;
}

