/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionType } from './transactionType';
import { TransactionMode } from './transactionMode';
import { TransactionStatus } from './transactionStatus';


export interface TransactionRequestDTO { 
    refNo?: string | null;
    amount?: number;
    status?: TransactionStatus;
    type?: TransactionType;
    mode?: TransactionMode;
    tenantId?: number;
    groupId?: number;
}
export namespace TransactionRequestDTO {
}


