/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionSummaryDto { 
    name?: string | null;
    refNo?: string | null;
    feeType?: string | null;
    amount?: number;
    date?: string;
}

