/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionRequestDTO { 
    groupMemberRefNO?: string | null;
    targetAccountId?: string | null;
    transactionDate?: string;
    amount?: number;
    transId?: string | null;
    status?: string | null;
    type?: string | null;
    mode?: string | null;
    receiptNumber?: string | null;
    transactionReferenceId?: string | null;
    paymentStructureId?: number;
}

