/**
 * GroupManagementSystem API
 *
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id?: number;
    userName: string;
    name: string;
    surname: string;
    emailAddress: string;
    isActive?: boolean;
    fullName?: string | null;
    lastLoginTime?: string | null;
    creationTime?: string;
    roleNames?: Array<string> | null;
}

